version: 2.1

orbs:
  ft-snyk-orb: financial-times/ft-snyk-orb@0

references:
  #
  # Workspace
  #
  container_config_node: &container_config_node
    working_directory: ~/project
    docker:
      - image: cimg/node:14.18.3-browsers

  workspace_root: &workspace_root ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_key: &npm_cache_key cache-v001-{{ .Branch }}-{{ checksum "./package.json" }}

  #
  # Cache creation
  #
  create_cache: &create_cache
    save_cache:
      key: *npm_cache_key
      paths:
        - ./node_modules/

  #
  # Cache restoration
  #
  restore_cache: &restore_cache
    restore_cache:
      keys:
        - *npm_cache_key

  #
  # Filters
  #
  only_version_tags: &only_version_tags
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta)\.\d+)?$/

jobs:
  build:
    <<: *container_config_node
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Create dotfiles
          command: make .editorconfig .eslintrc.js .eslintignore .prettierrc.js .prettierignore
      - *create_cache
      # - run:
      #     name: Fetch environment variables
      #     command: make env WHO=ci
      - run:
          name: Run build
          command: make build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test:
    <<: *container_config_node
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: make test

  publish:
    <<: *container_config_node
    steps:
      - *attach_workspace
      - run:
          name: npm publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
            make npm-publish

workflows:
  build-test-publish:
    jobs:
      - build:
          context: rel-eng-creds
          filters:
            <<: *only_version_tags
      - test:
          context: rel-eng-creds
          requires:
            - build
          filters:
            <<: *only_version_tags
      #Scan package.json for vulnerable dependencies while developing
      - ft-snyk-orb/scan-js-packages:
          context: rel-eng-creds
          requires:
            - build
          filters:
            <<: *only_version_tags
      - publish:
          context: rel-eng-creds
          requires:
            - test
            - ft-snyk-orb/scan-js-packages
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/
      #Scan and monitor vulnerabilities once in production
      - ft-snyk-orb/scan-and-monitor-js-packages:
          name: snyk-scan-and-monitor
          context: rel-eng-creds
          requires:
            - publish
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/

experimental:
  notify:
    branches:
      only:
        - main
