version: 2.1

orbs:
  ft-snyk-orb: financial-times/ft-snyk-orb@0

references:

  container_config_node8: &container_config_node8
    working_directory: ~/project/build
    docker:
      - image: circleci/node:8-browsers

  workspace_root: &workspace_root
    ~/project

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  npm_cache_keys: &npm_cache_keys
    keys:
        - v2-dependency-npm-{{ checksum "package.json" }}-
        - v2-dependency-npm-{{ checksum "package.json" }}
        - v2-dependency-npm-

  cache_npm_cache: &cache_npm_cache
    save_cache:
        key: v2-dependency-npm-{{ checksum "package.json" }}-{{ epoch }}
        paths:
        - ./node_modules/

  restore_npm_cache: &restore_npm_cache
    restore_cache:
        <<: *npm_cache_keys

  filters_ignore_tags: &filters_ignore_tags
    tags:
      ignore: /.*/

  filters_version_tag: &filters_version_tag
    tags:
      only:
        - /^v[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.\d+)?$/
    branches:
      ignore: /.*/

jobs:

  build:
    <<: *container_config_node8
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Install project dependencies
          command: npm install
      - run:
          name: Run the project build task
          command: make build
      - *cache_npm_cache
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - build

  test:
    <<: *container_config_node8
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: make test

  publish:
    <<: *container_config_node8
    steps:
      - *attach_workspace
      - run:
          name: npm publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
            make npm-publish

workflows:

  build-test:
    jobs:
      - build:
          filters:
            <<: *filters_ignore_tags
      - test:
          filters:
            <<: *filters_ignore_tags
          requires:
            - build
      - ft-snyk-orb/scan-js-packages:
          context: rel-eng-creds
          filters:
            <<: *filters_ignore_tags
          requires:
            - build

  build-test-publish:
    jobs:
      - build:
          filters:
            <<: *filters_version_tag
      - test:
          filters:
            <<: *filters_version_tag
          requires:
            - build
      - ft-snyk-orb/scan-js-packages:
          context: rel-eng-creds
          filters:
            <<: *filters_version_tag
          requires:
            - build
      - publish:
          context: rel-eng-creds
          filters:
            <<: *filters_version_tag
          requires:
            - test
            - ft-snyk-orb/scan-js-packages

experimental:
  notify:
    branches:
      only:
        - master
