on: [issues, pull_request]
jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: Sync repository labels
    steps:
      - uses: Financial-Times/rel-eng-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
